apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce-products
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: e-commerce-products
    spec:
      containers:
        - image: mahadidevo/e-commerce-products:v1.0.0
          name: e-commerce-products-container
          imagePullPolicy: Always
          ports:
            - containerPort: 4070
          livenessProbe:
            httpGet:
              path: /health
              port: 4070
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 4070
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"